version: '3.8'

services:
  kerridge-functions:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app

    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/kerridge/data
    environment:
      POSTGRES_USER: db_root
      POSTGRES_DB: kerridge-functions
      POSTGRES_PASSWORD: test
    ports:
     - "5002:5002"

volumes:
  postgres-data:
